name: english_study
description: "English Study App - YouTube-based English learning with interactive transcripts"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Audio playback for dictionary
  audioplayers: ^6.1.0

  # Background audio playbook
  audio_service: ^0.18.12

  # UI Components
  cupertino_icons: ^1.0.2

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Toast messages
  fluttertoast: ^8.2.4

  # HTTP requests
  http: ^1.1.0

  # Audio playback
  just_audio: ^0.9.36

  # State management
  provider: ^6.0.5

  # Local storage
  shared_preferences: ^2.2.2

  # URL handling
  url_launcher: ^6.1.14

  # Wake lock for preventing sleep
  wakelock_plus: ^1.1.4

  # XML parsing
  xml: ^6.4.2

  # YouTube audio extraction
  youtube_explode_dart: ^2.2.1

  # YouTube Player
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Include environment variables file
  assets:
    - .env