name: english_study
description: "English Study App - YouTube-based English learning with interactive transcripts"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2

  # YouTube Player
  youtube_player_flutter: ^9.1.1

  # Google Sign-In
  google_sign_in: ^6.1.5

  # HTTP requests
  http: ^1.1.0

  # XML parsing
  xml: ^6.4.2

  # State management
  provider: ^6.0.5

  # URL handling
  url_launcher: ^6.1.14

  # Background audio playback
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  
  # YouTube audio extraction
  youtube_explode_dart: ^2.2.1
  
  # Wake lock for preventing sleep
  wakelock_plus: ^1.1.4

  # Local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true